---
title: "Untitled"
author: "Andrew Barr"
date: "October 20, 2015"
output: html_document
---

```{r}
library(ape)
library(NullTurnover)
library(ggplot2)
library(parallel)
library(dplyr)
theme_set(theme_bw(20))
knitr::opts_knit$set(fig.width=10, fig.height=10)
```

Trees produced by `phytools::pbtree(bibiP, bibiQ, n=50, t=10)`, using the per interval Foote rate average for the period examined by Bibi & Kiessling. 

```{r}
treez <- readRDS("~/Dropbox/TurnoverPulseRedux/treez.Rdata")
```

## Criterion

```{r cache=TRUE}
criteria <- seq(1.2, 1.9, 0.1)
criterionPulses <- mclapply(criteria, mc.cores=4, FUN=function(criterion){
  pulses <- sapply(treez, FUN=function(theTree){
    return(detectPulses(theTree, desiredBinNumber = 20, criterion = criterion)[[1]])
    })
  return(sum(pulses > 0) / length(pulses))
  })
```

```{r}
qplot(xmin=criteria - 0.03, xmax=criteria + 0.03, ymin=0, ymax=unlist(criterionPulses), geom="rect") + 
  scale_x_continuous(breaks=criteria) + 
  labs(x="Turnover pulse criterion (* IQR)", y="Proportion trees with pulses")
```

## Sample size

```{r cache=TRUE}
nTaxa <- sapply(treez, FUN=function(tree) {
  length(tree$tip.label)
})

summary(nTaxa)

nPulses <- sapply(treez, FUN=function(tree){
  detectPulses(tree, desiredBinNumber = 20)
})
summary(nPulses)
```

```{r cache=TRUE}

summary(lm(nTaxa~factor(nPulses)))

qplot(factor(nPulses), nTaxa, geom="boxplot", fill=factor(nPulses)) + 
  scale_fill_brewer(palette = "Blues", guide="none") + 
  labs(x="number of pulses detected", y="number of taxa") + 
  coord_flip()

qplot(factor(nPulses), nTaxa, geom="violin", fill=factor(nPulses)) + 
  scale_fill_brewer(palette = "Blues", guide="none") + 
  labs(x="number of pulses detected", y="number of taxa") + 
  coord_flip()

```

## Bin number

*  For each bin number between 10 and 20, inclusive.
*  detect the number of pulses for each of the 2000 trees

```{r cache=TRUE}
binNumberPulses <- mclapply(10:20, mc.cores=4, FUN=function(binNumber) {
 nPulses <- sapply(treez, FUN=function(theTree){
    return(detectPulses(theTree, desiredBinNumber = binNumber))
    })
 return(list(binNumber = binNumber, nPulses=nPulses))
})

binNumberPulses <- lapply(binNumberPulses, FUN=function(x){
  data.frame(nPulses=x$nPulses, binNumber=rep(x$binNumber, length(x$nPulses)), nTaxa=nTaxa, treeID= 1:length(x$nPulses))
})

binNumberPulses <- do.call(rbind, binNumberPulses)

#sample one from each tree
binNumberPulses <- binNumberPulses %>% group_by(treeID) %>% sample_n(size=1)
```

```{r cache=TRUE}
ggplot(subset(binNumberPulses, binNumber %in% c(10,12,14,16,18,20)), aes(x=factor(nPulses), fill=factor(nPulses))) + 
  geom_bar(color="black") +
  facet_grid(binNumber~.) + 
  labs(x="Number of Pulses Detected") + 
  guides(fill=FALSE) + 
  scale_fill_brewer(palette = "Blues", name="bins") +
  coord_flip()

```

```{r cache=TRUE}
binNumberPulseCount <- binNumberPulses %>% 
  group_by(binNumber, nPulses) %>%
  summarize(count=n())
```

```{r cache=TRUE}
ggplot(subset(binNumberPulseCount, nPulses<4 & binNumber %in% c(10, 12, 14, 16, 18, 20)), aes(x=nPulses, y=count, fill=factor(binNumber), group=binNumber)) + 
  geom_bar(stat="identity", position="dodge", color="grey20") + 
  scale_fill_brewer(palette = "Blues", name="bins") + 
  labs(x="number of pulses detected") 
```

```{r cache=TRUE}
ggplot(binNumberPulses, aes(x=1, y=nPulses, size=nTaxa)) + 
  geom_point(alpha=1/10) + 
  facet_grid(~binNumber) + 
  scale_x_discrete(labels="") + 
  scale_size_continuous("Taxa in Tree") + 
  theme(axis.ticks.x=element_blank()) + 
  guides(size = guide_legend(override.aes = list(alpha = 1))) + 
  labs(x="number of bins", y="number of pulses detected")
```

```{r cache=TRUE}
ggplot(subset(binNumberPulses,binNumber %in% c(10, 12, 14, 16, 18, 20)), aes(x=nPulses, y=nTaxa)) + 
  geom_point(alpha=1/5, size=10) +
  facet_grid(binNumber~.)
```

```{r cache=TRUE}
ggplot(binNumberPulses, aes(x=factor(nPulses), y=nTaxa / binNumber, fill=factor(nPulses))) + 
  geom_boxplot() + 
  scale_fill_brewer(palette = "Blues", guide='none') + 
  labs(x="number of pulses detected", y="mean number of taxa per bin") + 
  coord_flip()

ggplot(binNumberPulses, aes(x=factor(nPulses), y=nTaxa / binNumber, fill=factor(nPulses))) + 
  geom_violin() + 
  scale_fill_brewer(palette = "Blues", guide='none') + 
  labs(x="number of pulses detected", y="mean number of taxa per bin") + 
  coord_flip()

summary(lm(nTaxa / binNumber ~ factor(nPulses), data=binNumberPulses))

```

```{r cache=TRUE}
ggplot(binNumberPulses, aes(x=factor(nPulses), y=binNumber,fill=factor(nPulses))) + 
  geom_boxplot() + 
  scale_fill_brewer(palette = "Blues", guide='none') + 
  labs(x="number of pulses detected", y="number of time bins") + 
  scale_y_continuous(breaks=seq(10, 20, 2)) + 
  coord_flip()

ggplot(binNumberPulses, aes(x=factor(nPulses), y=binNumber,fill=factor(nPulses))) + 
  geom_violin() + 
  scale_fill_brewer(palette = "Blues", guide='none') + 
  labs(x="number of pulses detected", y="number of time bins") + 
  scale_y_continuous(breaks=seq(10, 20, 2)) + 
  coord_flip()

summary(lm(binNumber ~ factor(nPulses), data=binNumberPulses))
```

## How many intervals have at least one pulse, of those with less than 10 taxa per interval

```{r cache=TRUE}
forPlot <- binNumberPulses %>% 
  mutate(taxaPerBin = nTaxa/binNumber) %>% 
  filter(taxaPerBin < 10) %>% 
  group_by(binNumber) %>%
  summarize(intervalsWithPulses = sum(nPulses>0)/length(nPulses))

forPlot %>% summarize(mean=mean(intervalsWithPulses))

qplot(data=forPlot, xmin=binNumber-0.2, xmax=binNumber+0.2, ymin=0,ymax=intervalsWithPulses, geom="rect") + 
    theme_bw(20) + 
    scale_x_continuous(breaks=10:20) + 
    labs(x="number of bins", y="proportion of trees with pulses")
```

